from pathlib import Path

import pytest

from builder2ibek.migrate_autosave import (
    IBEK_POSITIONS,
    IBEK_SETTINGS,
    find_legacy_set,
    migrate_folder,
    reformat,
)

# legacy pass-0 set: positions-like PVs, explicit .VAL fields
LEGACY_0 = """\
# autosave R5.3\tAutomatically generated - DO NOT MODIFY
BL19I-VA-GAUGE-05:ILKSETSP:NOWRITE.VAL 1
BL19I-RS-RDMON-01:MANRESETTIME.VAL 2013-06-11 08:46:05 UTC
<END>
"""

# legacy pass-1 set: settings (temperatures)
LEGACY_1 = """\
# autosave R5.3\tAutomatically generated - DO NOT MODIFY
BL19I-AL-SLITS-01:A:TEMP1:HIGH.VAL 60
<END>
"""

# legacy pass-1 set: just ACCESS
LEGACY_2 = """\
# autosave R5.3\tAutomatically generated - DO NOT MODIFY
BL19I-VA-IOC-01:ACCESS.VAL 0
<END>
"""


def _write_set(folder: Path, stem: str = "BL19I-VA-IOC-01"):
    (folder / f"{stem}_0.sav").write_text(LEGACY_0)
    (folder / f"{stem}_1.sav").write_text(LEGACY_1)
    (folder / f"{stem}_2.sav").write_text(LEGACY_2)


def test_reformat_strips_val_and_wraps(tmp_path: Path):
    f = tmp_path / "BL19I-VA-IOC-01_0.sav"
    f.write_text(LEGACY_0)

    lines, n = reformat([f])

    assert n == 2
    assert lines[0].startswith("# generated by builder2ibek")
    assert lines[-1] == "<END>"
    # .VAL dropped, string value with spaces preserved
    assert "BL19I-VA-GAUGE-05:ILKSETSP:NOWRITE 1" in lines
    assert "BL19I-RS-RDMON-01:MANRESETTIME 2013-06-11 08:46:05 UTC" in lines


def test_reformat_dedupes_last_wins(tmp_path: Path):
    a = tmp_path / "a.sav"
    a.write_text("PV:X.VAL 1\n<END>\n")
    b = tmp_path / "b.sav"
    b.write_text("PV:X.VAL 2\n<END>\n")

    lines, n = reformat([a, b])
    assert n == 1
    assert "PV:X 2" in lines


def test_find_legacy_set_returns_numbered_paths(tmp_path: Path):
    _write_set(tmp_path)
    # noise that must be ignored
    (tmp_path / "BL19I-VA-IOC-01_0.sav0").write_text("x")
    (tmp_path / "BL19I-VA-IOC-01_0.sav_260611-091551").write_text("x")

    sets = find_legacy_set(tmp_path)
    assert set(sets) == {0, 1, 2}
    assert sets[0].name == "BL19I-VA-IOC-01_0.sav"


def test_find_legacy_set_stem_disambiguates(tmp_path: Path):
    _write_set(tmp_path)
    (tmp_path / "BL19I_0.sav").write_text(LEGACY_0)

    with pytest.raises(ValueError, match="more than one autosave stem"):
        find_legacy_set(tmp_path)

    sets = find_legacy_set(tmp_path, stem="BL19I-VA-IOC-01")
    assert set(sets) == {0, 1, 2}

    with pytest.raises(ValueError, match="available stems: BL19I, BL19I-VA-IOC-01"):
        find_legacy_set(tmp_path, stem="NOPE")


def test_migrate_folder_maps_sets_to_files(tmp_path: Path):
    _write_set(tmp_path)

    migrate_folder(tmp_path, tmp_path)

    positions = (tmp_path / IBEK_POSITIONS).read_text()
    settings = (tmp_path / IBEK_SETTINGS).read_text()

    # set 0 -> positions
    assert "BL19I-VA-GAUGE-05:ILKSETSP:NOWRITE 1" in positions
    # sets 1 and 2 -> settings
    assert "BL19I-AL-SLITS-01:A:TEMP1:HIGH 60" in settings
    assert "BL19I-VA-IOC-01:ACCESS 0" in settings
    # ACCESS must not have leaked into positions
    assert "ACCESS" not in positions
    assert positions.endswith("<END>\n")
    assert settings.endswith("<END>\n")


def test_migrate_folder_removes_roundrobin_keeps_dated(tmp_path: Path):
    _write_set(tmp_path)
    for sfx in ("0", "1", "2", "B"):
        (tmp_path / f"{IBEK_POSITIONS}{sfx}").write_text("stale")
    dated = tmp_path / f"{IBEK_POSITIONS}_260611-091551"
    dated.write_text("archive")

    migrate_folder(tmp_path, tmp_path)

    for sfx in ("0", "1", "2", "B"):
        assert not (tmp_path / f"{IBEK_POSITIONS}{sfx}").exists()
    assert dated.exists()
    assert (tmp_path / IBEK_POSITIONS).exists()


def test_migrate_folder_separate_output_does_not_touch_input(tmp_path: Path):
    src = tmp_path / "in"
    dst = tmp_path / "out"
    src.mkdir()
    dst.mkdir()
    _write_set(src)

    migrate_folder(src, dst)

    # legacy inputs untouched, ibek files written only to output
    assert (src / "BL19I-VA-IOC-01_0.sav").read_text() == LEGACY_0
    assert not (src / IBEK_POSITIONS).exists()
    assert "ILKSETSP:NOWRITE 1" in (dst / IBEK_POSITIONS).read_text()
