#!/usr/bin/env python3
"""Vendor the ibek-support-dls entity models that the samples need.

ibek-support-dls lives on Diamond's internal GitLab, so CI cannot clone it and
9 of the 14 samples are skipped there -- including every vacuum IOC, which is
where the dlsPLC and ipac logic lives. This keeps a checked in copy of just the
support YAMLs those samples need, so CI can exercise them.

Only ``*/*.ibek.support.yaml`` is copied. update-schema symlinks exactly that
glob into ibek-defs, and support_defaults reads the same one, so nothing else in
the module folders is ever consulted by a test.

    --update    refresh tests/vendored-support-dls/ from the checked out
                submodule, which must be at the pin committed in this repo
    --install   populate ibek-support-dls/ from the vendored copy, for
                environments that cannot reach GitLab (i.e. CI)

The vendored tree deliberately does *not* sit under a path matching the
``ibek-support*`` glob, so a normal local checkout never sees it: the real
submodule stays the only source of entity models for conversion work. --install
refuses to touch a submodule that already has content.

Standard library only -- --install has to run in CI before any venv exists.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SAMPLES = REPO_ROOT / "tests" / "samples"
VENDORED = REPO_ROOT / "tests" / "vendored-support-dls"
DLS = REPO_ROOT / "ibek-support-dls"
COMMUNITY = REPO_ROOT / "ibek-support"
PIN_FILE = VENDORED / "VENDORED_FROM"

SUPPORT_GLOB = "*/*.ibek.support.yaml"

# Written by --update, which wipes the tree first, so it cannot be hand placed.
README = """\
# Vendored ibek-support-dls entity models

Generated by `tests/vendor_support_dls.py --update`. **Do not hand edit** --
`test_vendored_support.py` fails if these drift from the pinned submodule, and
`--update` deletes this whole directory before rewriting it.

`ibek-support-dls` lives on Diamond's internal GitLab, which GitHub Actions
cannot reach. Without this copy, 9 of the 14 samples skip in CI -- including
every vacuum IOC, so the `dlsPLC`, `ipac` and `vacuumValve` paths would never be
exercised.

Only `*/*.ibek.support.yaml` is copied. `update-schema` symlinks exactly that
glob into `ibek-defs` and `support_defaults` reads the same one, so nothing else
in a module folder is consulted.

## This is not a replacement for the submodule

The tree lives under `tests/` precisely so it does **not** match the
`ibek-support*` glob. A normal local checkout never sees it, and beamline
conversion work goes on using the real submodule as before. `--install` refuses
to touch an `ibek-support-dls/` that already has content; CI calls it because
there the submodule is empty.

## Refreshing it

After bumping the submodule pin:

```bash
git submodule update --checkout ibek-support-dls   # match the committed pin
python3 tests/vendor_support_dls.py --update
```

`--update` refuses to run against a submodule that is dirty or off the pin: the
vendored files have to correspond to a commit other people can fetch, so an
uncommitted edit must be pushed and the pin bumped first.

## Have I broken it?

```bash
python3 tests/vendor_support_dls.py --check
```

| result | meaning |
|---|---|
| `OK` | vendored copy matches the pinned submodule |
| `PENDING` | dls has uncommitted edits -- push them, bump the pin, then `--update` |
| `STALE` | pin moved, a module is missing, or content differs -- run `--update` |

`--check` is what `/support-create` and `/support-fix` call after touching
`ibek-support-dls/`. They report the result rather than acting on it, because
re-vendoring is impossible until the change is committed and pinned.
"""
_MODULE_RE = re.compile(r"^module:\s*(\S+)", re.M)
_ENTITY_TYPE_RE = re.compile(r"^\s*-?\s*type:\s*([A-Za-z0-9_-]+)\.", re.M)


def _module_index(repo: Path) -> dict[str, list[Path]]:
    """Map declared module name -> the support YAMLs declaring it.

    Keyed on the `module:` value rather than the folder name: they differ in
    case for several modules (IOCinfo lives in IOCInfo/, ADAndor in adandor/).
    """
    index: dict[str, list[Path]] = {}
    for support_yaml in repo.glob(SUPPORT_GLOB):
        match = _MODULE_RE.search(support_yaml.read_text())
        if match:
            index.setdefault(match.group(1), []).append(support_yaml)
    return index


def _modules_used_by_samples() -> set[str]:
    used: set[str] = set()
    for sample_yaml in SAMPLES.glob("*.yaml"):
        used |= set(_ENTITY_TYPE_RE.findall(sample_yaml.read_text()))
    return used


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=True
    ).stdout.strip()


def update() -> int:
    if not any(DLS.glob(SUPPORT_GLOB)):
        sys.exit(f"{DLS} has no support YAMLs -- git submodule update --init it first")

    # Vendor from the pin this repo commits, not from whatever happens to be
    # checked out, or the copy would not match what CI's sibling repos use.
    pinned = _git("ls-tree", "HEAD", "ibek-support-dls").split()[2]
    head = _git("-C", "ibek-support-dls", "rev-parse", "HEAD")
    if pinned != head:
        sys.exit(
            f"ibek-support-dls is at {head[:8]} but this repo pins {pinned[:8]}.\n"
            f"Check out the pin (git submodule update --checkout ibek-support-dls)\n"
            f"or commit the bump first."
        )

    # HEAD matching the pin is not enough: uncommitted edits would be copied in
    # and stamped with a SHA whose content they are not. The vendored tree has
    # to correspond to a commit somebody else can actually fetch.
    dirty = _git("-C", "ibek-support-dls", "status", "--porcelain")
    if dirty:
        sys.exit(
            "ibek-support-dls has uncommitted changes:\n"
            + "\n".join(f"  {line}" for line in dirty.splitlines())
            + "\nCommit and push them, bump the pin here, then re-run --update."
        )

    community = _module_index(COMMUNITY)
    dls = _module_index(DLS)
    used = _modules_used_by_samples()

    # Only what the samples actually need, and only what ibek-support cannot
    # already supply -- a module that moves to the community repo should drop
    # out of the vendored set on the next --update.
    needed = sorted(m for m in used if m in dls and m not in community)
    unresolved = sorted(m for m in used if m not in dls and m not in community)

    if VENDORED.exists():
        shutil.rmtree(VENDORED)
    VENDORED.mkdir(parents=True)

    copied = 0
    for module in needed:
        for src in dls[module]:
            dest = VENDORED / src.parent.name / src.name
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dest)
            copied += 1

    PIN_FILE.write_text(
        "# Generated by tests/vendor_support_dls.py --update -- do not hand edit.\n"
        f"ibek-support-dls {pinned}\n" + "".join(f"{m}\n" for m in needed)
    )
    (VENDORED / "README.md").write_text(README)

    print(f"vendored {copied} support YAMLs for {len(needed)} modules")
    print(f"  from ibek-support-dls {pinned[:8]}")
    print(f"  into {VENDORED.relative_to(REPO_ROOT)}")
    if unresolved:
        # Not fatal: ibek's own builtins (ibek.repeat and friends) land here,
        # as would a genuinely missing module -- which generate2 would then
        # fail on far more loudly than this script could.
        print(f"  not found in either support repo: {' '.join(unresolved)}")
    return 0


def install() -> int:
    if not any(VENDORED.glob(SUPPORT_GLOB)):
        sys.exit(
            f"{VENDORED} is empty -- run --update from a checkout with the submodule"
        )

    if any(DLS.glob(SUPPORT_GLOB)):
        # The real submodule wins, always. Refusing rather than merging keeps
        # exactly one source of entity models in play at a time.
        print(f"{DLS.name} already populated, leaving it alone")
        return 0

    pinned_line = PIN_FILE.read_text().splitlines()[1] if PIN_FILE.exists() else "?"
    copied = 0
    for src in sorted(VENDORED.glob(SUPPORT_GLOB)):
        dest = DLS / src.parent.name / src.name
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)
        copied += 1

    print(f"installed {copied} vendored support YAMLs into {DLS.name}/ ({pinned_line})")
    return 0


def check() -> int:
    """Report whether the vendored copy needs refreshing. Exit 1 if it does.

    For skills and workflows that edit ibek-support-dls: they cannot re-vendor
    themselves, because a copy can only be taken from a commit that is pushed
    and pinned here. So they call this and tell the user what is outstanding.
    """
    if not any(VENDORED.glob(SUPPORT_GLOB)):
        print("STALE: no vendored copy at all -- run --update")
        return 1

    pinned = _git("ls-tree", "HEAD", "ibek-support-dls").split()[2]
    recorded = (
        PIN_FILE.read_text().splitlines()[1].split()[1] if PIN_FILE.exists() else ""
    )
    if recorded != pinned:
        print(
            f"STALE: vendored from {recorded[:8] or '?'}, "
            f"but this repo pins {pinned[:8]}\n"
            f"  run: python3 tests/vendor_support_dls.py --update"
        )
        return 1

    if not any(DLS.glob(SUPPORT_GLOB)):
        print(
            f"OK (vendored from {pinned[:8]}); "
            f"submodule absent, cannot compare contents"
        )
        return 0

    dirty = _git("-C", "ibek-support-dls", "status", "--porcelain")
    if dirty:
        print(
            "PENDING: ibek-support-dls has uncommitted changes, so the vendored copy\n"
            "cannot be refreshed yet. Once they are pushed and the pin bumped here:\n"
            "  python3 tests/vendor_support_dls.py --update\n"
            "Uncommitted:\n" + "\n".join(f"  {line}" for line in dirty.splitlines())
        )
        return 1

    community = _module_index(COMMUNITY)
    dls = _module_index(DLS)
    needed = {m for m in _modules_used_by_samples() if m in dls and m not in community}
    missing = sorted(needed - set(_module_index(VENDORED)))
    differs = [
        f"{f.parent.name}/{f.name}"
        for f in sorted(VENDORED.glob(SUPPORT_GLOB))
        if not (DLS / f.parent.name / f.name).exists()
        or (DLS / f.parent.name / f.name).read_bytes() != f.read_bytes()
    ]
    if missing or differs:
        print("STALE: run python3 tests/vendor_support_dls.py --update")
        for m in missing:
            print(f"  module needed by samples but not vendored: {m}")
        for d in differs:
            print(f"  differs from submodule: {d}")
        return 1

    print(f"OK: vendored copy matches ibek-support-dls {pinned[:8]}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--update",
        action="store_true",
        help="refresh the vendored copy from the submodule",
    )
    group.add_argument(
        "--install",
        action="store_true",
        help="populate ibek-support-dls/ from the vendored copy",
    )
    group.add_argument(
        "--check", action="store_true", help="report whether the vendored copy is stale"
    )
    args = parser.parse_args()
    if args.update:
        return update()
    return install() if args.install else check()


if __name__ == "__main__":
    raise SystemExit(main())
