# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/
epicsEnvSet EPICS_CA_MAX_ARRAY_BYTES 6000000

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Autosave pre iocInit
set_requestfile_path("/epics", "autosave")
set_requestfile_path("/epics", "runtime")
set_savefile_path("/autosave")
save_restoreSet_status_prefix BL03I-MO-IOC-11:
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile autosave_positions.sav
# settings are restored at BOTH pass 0 (before iocInit) and pass 1
# (after iocInit), reproducing the legacy DLS level-1 semantics.
# Pass 0 is essential for records that self-initialise from their
# restored value at PINI - e.g. dlsPLC_temperature :HIGH, whose
# :HIGH_INIT calcout copies the restored :HIGH into the temperature
# record's .HIGH field during iocInit. With a pass-1-only restore
# that PINI runs before the value is restored and :HIGH collapses to
# 0. Pass 1 is also kept so PVs that get overwritten during init are
# restored on top afterwards.
set_pass0_restoreFile autosave_settings.sav
set_pass1_restoreFile autosave_settings.sav
# Create SSH Port (PortName, IPAddress, Username, Password, Priority, DisableAutoConnect, noProcessEos)
drvAsynPowerPMACPortConfigure("PPMAC01_PORT", "10.0.0.0", "root", "pytest", "0", "0", "0")
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("PPMAC01", "PPMAC01_PORT", 0, 8, 100, 1000)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("PPMAC01", 8)

dbLoadRecords /ioc.db
iocInit

# Autosave post iocInit
create_monitor_set autosave_positions.req, 5, ""
create_monitor_set autosave_settings.req, 30, ""
