# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TS_MIN_WEST 0
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK_1", "172.23.104.167")
# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK_2", "172.23.104.168")
# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK_3", "172.23.104.169")
# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK_4", "172.23.104.170")
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("GeoBrick_1", "BRICK_1", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("GeoBrick_1", 8)
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("GeoBrick_2", "BRICK_2", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("GeoBrick_2", 8)
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("GeoBrick_3", "BRICK_3", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("GeoBrick_3", 8)
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("GeoBrick_4", "BRICK_4", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("GeoBrick_4", 8)
pmacDisableLimitsCheck("GeoBrick_1", 1, 0)
pmacDisableLimitsCheck("GeoBrick_1", 2, 0)
pmacDisableLimitsCheck("GeoBrick_1", 3, 0)
pmacDisableLimitsCheck("GeoBrick_1", 4, 0)
pmacDisableLimitsCheck("GeoBrick_1", 5, 0)
pmacDisableLimitsCheck("GeoBrick_1", 6, 0)
pmacDisableLimitsCheck("GeoBrick_1", 7, 0)
pmacDisableLimitsCheck("GeoBrick_3", 5, 0)
pmacDisableLimitsCheck("GeoBrick_4", 6, 0)
# Autosave pre iocInit
set_requestfile_path("/epics", "autosave")
set_requestfile_path("/epics", "runtime")
set_savefile_path("/autosave")
save_restoreSet_status_prefix BL04I-MO-IOC-03:
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile autosave_positions.sav
set_pass1_restoreFile autosave_settings.sav
seq recover, "P=BL04I-MO-FSWT-01"
asSetFilename /epics/support/pvlogging/src/access.acf
set_logging_enable 1
set_max_array_length 10

dbLoadRecords /ioc.db
iocInit

dbpf "BL04I-MO-STEP-04:AXIS5:DESC" "{'FSWT Transition'}"
dbpf "BL04I-MO-STEP-04:AXIS6:DESC" "{'FSWT Rocker'}"
# Autosave post iocInit
create_monitor_set autosave_positions.req, 5, ""
create_monitor_set autosave_settings.req, 30, ""
