# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TS_MIN_WEST 0
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/
epicsEnvSet Vec1 192
epicsEnvSet Vec2 193
epicsEnvSet Vec3 194
epicsEnvSet Vec4 195
epicsEnvSet Vec5 196
epicsEnvSet Vec6 197
epicsEnvSet Vec7 198

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

asSetFilename /epics/support/pvlogging/src/access.acf
set_logging_enable 1
set_max_array_length 10
# Autosave pre iocInit
set_requestfile_path("/epics", "autosave")
set_requestfile_path("/epics", "runtime")
set_savefile_path("/autosave")
save_restoreSet_status_prefix BL04I-VA-IOC-01:
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile autosave_positions.sav
set_pass1_restoreFile autosave_settings.sav

# ErConfigurePMC card_id card_index
ErConfigurePMC 1 0

# ipacAddHy8002("slot, intLevel")
ipacAddHy8002("4, 2")
# record above carrier card ID 0 in 'BL04I-VA-IOC-01.Slot4'
epicsEnvSet BL04I-VA-IOC-01.Slot4 0
ipacAddHy8002("5, 2")
# record above carrier card ID 1 in 'BL04I-VA-IOC-01.Slot5'
epicsEnvSet BL04I-VA-IOC-01.Slot5 1

#  Hy8001Configure(cardNum, vmeslotNum, vectorNum, itrLevel, debounce, clock, scan, direction, invertin, invertout)
Hy8001Configure(60, 6, $(Vec2), 0, 0, 0, 100, 0, 1, 1)

# DLS8515Configure(card id, carrier_index, interrupt_vector)
DLS8515Configure(40, $(BL04I-VA-IOC-01.Slot4), $(Vec3))
DLS8515Configure(42, $(BL04I-VA-IOC-01.Slot4), $(Vec4))

# DLS8516Configure(card_id, carrier_index, interrupt_vector)
DLS8516Configure(41, $(BL04I-VA-IOC-01.Slot4), $(Vec5))

# drvAsynSerialPortConfigure(name, port, priority, noAutoConnect, noProcessEos)
drvAsynSerialPortConfigure("ty_40_0", "/dev/tty400" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_1", "/dev/tty401" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_2", "/dev/tty402" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_3", "/dev/tty403" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_4", "/dev/tty404" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_5", "/dev/tty405" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_6", "/dev/tty406" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_40_7", "/dev/tty407" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_41_0", "/dev/tty410" , 0, 0, 0)
drvAsynSerialPortConfigure("ty_42_0", "/dev/tty420" , 0, 0, 0)

# drvAsynIPPortConfigure(name, port, priority, noAutoConnect, noProcessEos)
drvAsynIPPortConfigure(LPORT, 172.23.226.231:7016, 100, 0, 0)
asynOctetSetInputEos(LPORT, 0, "\r\n")

# serial port settings from DL8515Channel
asynSetOption("ty_40_0",0,"baud",57600)
asynSetOption("ty_40_0",0,"bits",7)
asynSetOption("ty_40_0",0,"stop",2)

asynSetOption("ty_40_1",0,"baud",38400)


# serial port settings from DL8516Channel

# Hy8401ipConfigure(cardNum, VMESlotNum, IPSlotNum, interruptVector, intEnable, aiType, externalClock, clockRate, inhibit, samples, spacing, triggered)
Hy8401ipConfigure(50, $(BL04I-VA-IOC-01.Slot5), 0, $(Vec6), 0, 0, 0, 15, 0, 1, 1, 0)

# Hy8402ipConfigure(cardNum, VMESlotNum, IPSlotNum, interruptVector, doRam, externalClock, clockRate, inhibit)
Hy8402ipConfigure(51, $(BL04I-VA-IOC-01.Slot5), 1, $(Vec7), 0, 0, 13, 0)
initHy8402ipAsyn("BL04I-VA-IOC-01.Slot5.B", 51)

dbLoadRecords /ioc.db
iocInit

# Autosave post iocInit
create_monitor_set autosave_positions.req, 5, ""
create_monitor_set autosave_settings.req, 30, ""
