# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TS_MIN_WEST 0
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Autosave pre iocInit
set_requestfile_path("/epics", "autosave")
set_requestfile_path("/epics", "runtime")
set_savefile_path("/autosave")
save_restoreSet_status_prefix BL11I-CS-IOC-09:
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile autosave_positions.sav
set_pass1_restoreFile autosave_settings.sav
asSetFilename /epics/support/pvlogging/src/access.acf
set_logging_enable 1
set_max_array_length 10

# drvAsynIPPortConfigure(name, port, priority, noAutoConnect, noProcessEos)
drvAsynIPPortConfigure(rgaPort, 10.111.5.1:5025, 100, 0, 0)

dbLoadRecords /ioc.db
iocInit

# Autosave post iocInit
create_monitor_set autosave_positions.req, 5, ""
create_monitor_set autosave_settings.req, 30, ""

seq(sncDegas, "P=BL11I-EA-RGA-01")
