# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

asSetFilename /epics/support/pvlogging/src/access.acf
set_logging_enable 1
set_max_array_length 10
load_logging_blacklist /epics/ioc/config/pvlogging_excl.txt

dbLoadRecords /ioc.db
iocInit
