# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/
epicsEnvSet EPICS_CA_MAX_ARRAY_BYTES 6000000

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK1port", "172.23.59.21:1025")
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("BRICK1", "BRICK1port", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("BRICK1", 8)
pmacDisableLimitsCheck("BRICK1", 2, 0)
pmacDisableLimitsCheck("BRICK1", 3, 0)
pmacDisableLimitsCheck("BRICK1", 4, 0)
pmacDisableLimitsCheck("BRICK1", 5, 0)
# Create CS (CSPortName, ControllerPort, CSNumber, ProgramNumber)
pmacCreateCS("BRICK1.CS1", "BRICK1", 1, 10)
# Configure Model 3 CS Axes Driver (CSPortName, CSAxisCount)
pmacCreateCSAxes("BRICK1.CS1", 9)
# Create CS (CSPortName, ControllerPort, CSNumber, ProgramNumber)
pmacCreateCS("BRICK1.CS2", "BRICK1", 2, 10)
# Configure Model 3 CS Axes Driver (CSPortName, CSAxisCount)
pmacCreateCSAxes("BRICK1.CS2", 9)
# Create CS (CSPortName, ControllerPort, CSNumber, ProgramNumber)
pmacCreateCS("BRICK1.CS3", "BRICK1", 3, 10)
# Configure Model 3 CS Axes Driver (CSPortName, CSAxisCount)
pmacCreateCSAxes("BRICK1.CS3", 9)
pmacCreateCsGroup("BRICK1", 0, "Default", 9)
pmacCsGroupAddAxis(BRICK1, 0, 2, I, 2)
pmacCsGroupAddAxis(BRICK1, 0, 3, I, 2)
pmacCsGroupAddAxis(BRICK1, 0, 6, Z, 3)
pmacCsGroupAddAxis(BRICK1, 0, 7, I, 3)
pmacCsGroupAddAxis(BRICK1, 0, 8, I, 3)

dbLoadRecords /ioc.db
iocInit
