# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TZ GMT0BST
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK_2", "172.23.104.168")
# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("GeoBrick_2", "BRICK_2", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("GeoBrick_2", 8)

dbLoadRecords /ioc.db
iocInit
