# EPICS IOC Startup Script generated by https://github.com/epics-containers/ibek

cd ""

epicsEnvSet EPICS_TS_MIN_WEST 0
epicsEnvSet STREAM_PROTOCOL_PATH /epics/runtime/protocol/
epicsEnvSet EPICS_CA_AUTO_ADDR_LIST NO
epicsEnvSet EPICS_CA_ADDR_LIST 172.23.207.255
epicsEnvSet EPICS_CAS_AUTO_BEACON_ADDR_LIST NO
epicsEnvSet EPICS_CAS_BEACON_ADDR_LIST 172.23.194.105

dbLoadDatabase dbd/ioc.dbd
ioc_registerRecordDeviceDriver pdbbase

# Autosave pre iocInit
set_requestfile_path("/epics", "autosave")
set_requestfile_path("/epics", "runtime")
set_savefile_path("/autosave")
save_restoreSet_status_prefix SR03C-VA-IOC-01:
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile autosave_positions.sav
set_pass1_restoreFile autosave_settings.sav

# drvAsynIPPortConfigure(name, port, priority, noAutoConnect, noProcessEos)
drvAsynIPPortConfigure(GCTLR_A_01_PORT, 192.168.3.11:7002, 100, 0, 0)
drvAsynIPPortConfigure(GCTLR_S_01_PORT, 192.168.3.11:7003, 100, 0, 0)
drvAsynIPPortConfigure(MPC_S_01_PORT, 192.168.3.11:7004, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_01_PORT, 192.168.3.11:7005, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_02_PORT, 192.168.3.11:7006, 100, 0, 0)
drvAsynIPPortConfigure(RGA_PC_01_PORT, 192.168.3.12:7001, 100, 0, 0)
drvAsynIPPortConfigure(GCTLR_A_02_PORT, 192.168.3.12:7003, 100, 0, 0)
drvAsynIPPortConfigure(GCTLR_A_03_PORT, 192.168.3.12:7004, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_03_PORT, 192.168.3.12:7005, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_04_PORT, 192.168.3.12:7006, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_05_PORT, 192.168.3.12:7007, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_06_PORT, 192.168.3.12:7008, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_07_PORT, 192.168.3.12:7009, 100, 0, 0)
drvAsynIPPortConfigure(MPC_A_08_PORT, 192.168.3.12:7010, 100, 0, 0)

# finsUDPInit(asyn_port, ip_addr)
finsUDPInit("VLVCC_01_FINS", "192.168.3.10")

# EtherIP Initialisation
drvEtherIP_init()
# Define EtherIP to PLC connection
drvEtherIP_define_PLC("VLVCC_01_EIP", "192.168.3.10", 0)

dbLoadRecords /ioc.db
iocInit

# Autosave post iocInit
create_monitor_set autosave_positions.req, 5, ""
create_monitor_set autosave_settings.req, 30, ""
