#!/usr/bin/env python3
"""Render the sweep's committed skip report.

The skip report is a deliverable, not a diagnostic: it is the backlog for the
next phase of work, so it is generated from the JSON the sweep produced rather
than written by hand. It replaces `BUILD-TIME-ONLY.md` at the root of
ibek-runtime-streamdevice, which is already the repo's name for this list and is
linked from its README.

usage:
    render-report.py --outdir <sweep-workdir> \
                     --repo /workspaces/ibek-runtime-streamdevice \
                     > BUILD-TIME-ONLY.md

Reads eligibility.json, case-duplicates.json and descriptions.json from
<sweep-workdir> - all three are required, because a report that is quietly
missing a section is worse than no report - plus docs-skips.json, which is
optional because it is accumulated per module as the docs sweep is worked.

Anything below the NOTES_MARKER in the existing report is hand-written and is
carried through unchanged.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

# Everything below this line in BUILD-TIME-ONLY.md is hand-written analysis that
# no sweep can reproduce (which compiled device support a shipped pattern's
# records reference, and so on). It is read back out of the existing file and
# re-emitted, so re-running the sweep does not delete it.
NOTES_MARKER = "<!-- hand-written notes below this line survive the next sweep -->"

HEADER = """\
# Modules the runtime sweep did not turn into patterns

Generated by `.claude/skills/streamdevice-sweep` in
[builder2ibek](https://github.com/epics-containers/builder2ibek). Everything
above the hand-written-notes marker at the foot of this file is regenerated by
the sweep - edit it there, not here. Analysis that the sweep cannot reproduce
goes below that marker, where it survives.

A DLS support module becomes a runtime StreamDevice pattern only if it needs
**nothing in the IOC binary**. Two mechanical gates decide it:

1. **Filesystem** - no compiled code: no `*App/src/*.{{c,cpp,cc}}` (the
   makeBaseApp `<mod>Main.cpp` and the generated
   `*_registerRecordDeviceDriver.cpp` do not count), no module-authored
   `*App/src/*.dbd`, no SNL `.st`/`.stt`.
2. **`etc/builder.py`** - `LibFileList` and `DbdFileList` empty or absent, and
   `Dependencies` a subset of the modules the generic `ioc-streamdevice` image
   ships ({image}).

`Initialise` / `PostIocInitialise` emitting st.cmd lines is **not** a
disqualifier - `ibek` expresses those as `pre_init`/`post_init`.

Everything below needs its own generic IOC, or a decision.
"""


def load(path: Path, required: bool = False):
    if path.is_file():
        return json.loads(path.read_text())
    if required:
        sys.exit(
            f"{path} is missing - the report would be silently short of a whole "
            "section. Re-run run-sweep.sh."
        )
    return []


def hand_written_notes(repo: Path | None) -> str:
    """The existing report's hand-written tail, verbatim, marker included."""
    if repo is None:
        return ""
    existing = repo / "BUILD-TIME-ONLY.md"
    if not existing.is_file():
        return ""
    text = existing.read_text()
    if NOTES_MARKER not in text:
        print(
            f"note: {existing} has no hand-written-notes marker, so nothing was "
            "carried over. If it holds analysis the sweep cannot reproduce, move "
            "it below the marker in the new file (`git show HEAD:BUILD-TIME-ONLY.md`).",
            file=sys.stderr,
        )
        return ""
    return text[text.index(NOTES_MARKER) :].rstrip("\n")


def reason_bucket(entry: dict) -> str:
    g1 = entry["gate1"]["reasons"]
    g2 = entry["gate2"]["reasons"]
    if any("already shipped in the generic image" in r for r in g2):
        return "Already in the generic image - not a pattern"
    if any(r.startswith("compiled source") for r in g1):
        return "Ships compiled device code"
    if any("SNL" in r for r in g1):
        return "Needs a compiled SNL sequencer program"
    if any(r.startswith("module-authored dbd") for r in g1):
        return "Ships a module-authored `.dbd`"
    if any(r.startswith(("LibFileList", "DbdFileList")) for r in g2):
        return "Declares a library or dbd the image does not ship"
    if any("not-in-image" in r for r in g2):
        return "Depends on a support module the image does not ship"
    return "Other"


def table(rows: list[tuple[str, str, str]]) -> str:
    out = ["| Module | Release | Why |", "|---|---|---|"]
    out += [f"| `{n}` | `{v}` | {why} |" for n, v, why in rows]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", required=True, type=Path)
    ap.add_argument("--repo", type=Path, help="ibek-runtime-streamdevice checkout")
    args = ap.parse_args()

    elig = load(args.outdir / "eligibility.json", required=True)
    dups = load(args.outdir / "case-duplicates.json", required=True)
    descs = load(args.outdir / "descriptions.json", required=True)
    docskips = load(args.outdir / "docs-skips.json")  # accumulated per module
    image = load(args.outdir / "image-modules.json") or []
    shipped = (
        {
            p.name
            for p in args.repo.iterdir()
            if p.is_dir() and not p.name.startswith(".")
        }
        if args.repo
        else set()
    )

    print(
        HEADER.format(image=", ".join(f"`{m}`" for m in image) or "see the Dockerfile")
    )

    buckets: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    review: list[tuple[str, str, str]] = []
    regressions: list[tuple[str, str, str]] = []
    for e in elig:
        reasons = e["gate1"]["reasons"] + e["gate2"]["reasons"]
        why = "; ".join(f"`{r}`" if ":" in r else r for r in reasons[:3])
        if e["verdict"] == "SKIP":
            if e["name"] in shipped:
                regressions.append((e["name"], e["version"], why))
            else:
                buckets[reason_bucket(e)].append((e["name"], e["version"], why))
        elif e["verdict"] == "REVIEW":
            review.append((e["name"], e["version"], why))

    for bucket in sorted(buckets):
        print(f"\n## {bucket}\n")
        print(table(sorted(buckets[bucket])))

    if dups:
        print("\n## Case-duplicate modules - dropped from the candidate set\n")
        print(
            "`/dls_sw/prod` holds pairs of modules differing only in case, left behind "
            "when DLS renamed one. Two folders differing only in case collide on a "
            "case-insensitive clone, and `ibek pattern add` resolves a pattern by "
            "`clone_dir / name`, so it would silently pick up whichever landed. The "
            "variant with more releases and the later latest release wins.\n"
        )
        print(table(sorted((d["module"], "-", d["detail"]) for d in dups)))

    if review:
        print("\n## Needs a human decision\n")
        print(
            "These pass gate 1 but cannot be decided mechanically - usually because "
            "the module's `etc/builder.py` is missing, empty or defines no classes, "
            "so there is no entity-model source to convert from even though nothing "
            "disqualifies it.\n"
        )
        print(table(sorted(review)))

    if regressions:
        print("\n## Already shipped as a pattern, but fails a gate\n")
        print(
            "These folders exist in this repo and predate the mechanical gates. The "
            "sweep does **not** delete them - it reports them. Each needs a decision: "
            "trim the entity models that need the compiled support, move the pattern "
            "to a build-time `ibek-support` definition, or record why it is "
            "acceptable.\n"
        )
        print(table(sorted(regressions)))

    if docskips:
        print("\n## Documentation not copied\n")
        print(
            "This is a **public** repo and DLS `documentation/` folders routinely hold "
            "manufacturer datasheets and manuals that DLS has no right to "
            "redistribute. These are named here rather than copied; find them in the "
            "DLS module or from the manufacturer by part number.\n"
        )
        out = ["| Module | File | Why |", "|---|---|---|"]
        out += [
            f"| `{d['module']}` | `{d['file']}` | {d['reason']} |"
            for d in sorted(docskips, key=lambda d: (d["module"], d["file"]))
        ]
        print("\n".join(out))

    if descs:
        print("\n## Support yaml descriptions that need writing\n")
        print(
            "No per-pattern README is generated - `*.ibek.support.yaml` is meant to be "
            "self-documenting. That only holds if the descriptions are real.\n"
        )
        out = ["| Pattern | Where | Problem |", "|---|---|---|"]
        out += [
            f"| `{Path(d['file']).parent.name}` | {d['where']} | {d['reason']} |"
            for d in descs
        ]
        print("\n".join(out))

    notes = hand_written_notes(args.repo)
    print(f"\n---\n\n{notes}" if notes else f"\n---\n\n{NOTES_MARKER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
