"""
Migrate legacy DLS autosave .sav files to the ibek autosave .sav files.

Legacy DLS IOCs save to per-set files (``<IOC>_0.sav``, ``_1.sav``, ``_2.sav``)
with explicit field names (``PV.VAL value``). ibek IOCs restore from
``autosave_positions.sav`` (pass 0) and ``autosave_settings.sav`` (pass 1)
using the bare record name (``PV value``).

This is a naive conversion: the legacy set files are reformatted (a trailing
``.VAL`` is dropped) and written to the ibek files following the DLS pass
convention -- set 0 -> positions, sets 1+ -> settings. No knowledge of the new
IOC's PV set (its .req files) is needed: at restore autosave applies whatever
``PV value`` lines it finds and ignores any PV the IOC does not have, then
re-saves its own set on the first save. PVs the new IOC no longer carries are
therefore restored harmlessly and drop out by themselves.

The usual mode is folder-in / folder-out (both default to the cwd): it finds the
legacy ``<stem>_<N>.sav`` set in the input folder and writes the two ibek files
to the output folder, removing any round-robin sibling files so the IOC cannot
restore a stale one.
"""

import re
from pathlib import Path

IBEK_POSITIONS = "autosave_positions.sav"
IBEK_SETTINGS = "autosave_settings.sav"

# the current per-set save file for a legacy IOC: "<stem>_<N>.sav" exactly.
# dated backups (..._0.sav_230814-110051), sequence backups (..._0.sav0,
# ..._0.savB) and SBAD files all have extra characters after ".sav" and so are
# deliberately excluded -- this leaves only the most recent save of each set.
_LEGACY_RE = re.compile(r"^(?P<stem>.+)_(?P<n>\d+)\.sav$")

_VAL_SUFFIX = re.compile(r"\.VAL$")


def _normalise(pv: str) -> str:
    """Strip a single trailing ``.VAL`` so legacy ``PV.VAL`` matches ibek ``PV``."""
    return _VAL_SUFFIX.sub("", pv)


def _is_data(line: str) -> bool:
    """True for value lines; False for comments, blanks and the <END> marker."""
    s = line.strip()
    return bool(s) and not s.startswith("#") and not s.startswith("<END>")


def find_legacy_set(folder: Path, stem: str | None = None) -> dict[int, Path]:
    """
    Find the current legacy save set in ``folder`` as ``{set_number: path}``.

    Selects the ``<stem>_<N>.sav`` files -- the most recent save of each set
    (dated/sequence/SBAD backups are excluded). If ``stem`` is given only that
    stem's files are returned; otherwise the folder must contain exactly one
    stem. Raises if there are none, the requested stem is absent, or (with no
    ``stem``) more than one stem is present.
    """
    by_stem: dict[str, dict[int, Path]] = {}
    for p in sorted(folder.iterdir()):
        if not p.is_file():
            continue
        match = _LEGACY_RE.match(p.name)
        if match:
            by_stem.setdefault(match.group("stem"), {})[int(match.group("n"))] = p

    if not by_stem:
        raise FileNotFoundError(f"no legacy <stem>_<N>.sav files found in {folder}")

    if stem is not None:
        if stem not in by_stem:
            available = ", ".join(sorted(by_stem))
            raise ValueError(
                f"no {stem}_<N>.sav files found in {folder} "
                f"(available stems: {available})"
            )
        return by_stem[stem]

    if len(by_stem) > 1:
        stems = ", ".join(sorted(by_stem))
        raise ValueError(
            f"found more than one autosave stem in {folder}: {stems}. "
            "Select one with --from <stem>."
        )

    (sets,) = by_stem.values()
    return sets


def reformat(paths: list[Path]) -> tuple[list[str], int]:
    """
    Convert one or more legacy .sav files into ibek .sav lines.

    Each value line is rewritten with a trailing ``.VAL`` stripped; PVs are
    de-duplicated (last value wins) preserving first-seen order. Returns
    ``(lines, n_pvs)`` including the comment header and ``<END>`` marker.
    """
    values: dict[str, str] = {}
    for path in paths:
        for line in path.read_text(encoding="latin-1").splitlines():
            if not _is_data(line):
                continue
            parts = line.split(None, 1)
            values[_normalise(parts[0])] = parts[1] if len(parts) > 1 else ""

    lines = ["# generated by builder2ibek migrate-autosave"]
    lines += [f"{pv} {value}" for pv, value in values.items()]
    lines.append("<END>")
    return lines, len(values)


def _clean_sequence_files(dest: Path, dry_run: bool) -> None:
    """
    Remove autosave round-robin / boot-backup siblings of ``dest`` that could be
    picked up at restore (``<name>.sav0``, ``.sav1``, ``.sav2``, ``.savB``, ...).

    Only single-extra-character suffixes are matched (glob ``<name>?``), so the
    live file itself (``<name>``) and dated archives written on restart
    (``<name>_<date>``, ``...SBAD...``) are never touched.
    """
    for sibling in sorted(dest.parent.glob(dest.name + "?")):
        if dry_run:
            print(f"  (dry-run: would remove {sibling})")
        else:
            sibling.unlink()
            print(f"  removed {sibling}")


def _write_lines(dest: Path, out_lines: list[str], backup: bool, dry_run: bool) -> None:
    if dry_run:
        print(f"  (dry-run: {dest} not written)")
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    if backup and dest.exists():
        backup_path = dest.with_suffix(dest.suffix + ".bak")
        backup_path.write_bytes(dest.read_bytes())
        print(f"  backed up {dest} -> {backup_path}")
    dest.write_text("\n".join(out_lines) + "\n", encoding="latin-1")
    print(f"  wrote {dest}")


def migrate_folder(
    input_folder: Path = Path("."),
    output_folder: Path = Path("."),
    stem: str | None = None,
    backup: bool = True,
    clean: bool = True,
    dry_run: bool = False,
) -> None:
    """
    Convert the legacy save set in ``input_folder`` into the two ibek autosave
    files in ``output_folder`` (set 0 -> positions, sets 1+ -> settings).

    stem:    IOC stem selecting which ``<stem>_<N>.sav`` set to use; only needed
             when the input folder contains more than one stem
    backup:  copy an existing destination to ``<file>.bak`` before writing
    clean:   remove round-robin sibling files (``.sav0``/``.savB``/...) of each
             written target so the IOC cannot restore a stale one
    dry_run: report what would happen but write nothing
    """
    sets = find_legacy_set(input_folder, stem)
    print("legacy sets:")
    for n in sorted(sets):
        print(f"  {n}: {sets[n].name}")

    plan = {
        IBEK_POSITIONS: [sets[n] for n in sorted(sets) if n == 0],
        IBEK_SETTINGS: [sets[n] for n in sorted(sets) if n >= 1],
    }

    for name, srcs in plan.items():
        dest = output_folder / name
        if not srcs:
            print(f"\n{name}: no matching legacy set, skipping")
            continue
        out_lines, n_pvs = reformat(srcs)
        print(f"\n{name}: {n_pvs} PVs from {', '.join(s.name for s in srcs)}")
        _write_lines(dest, out_lines, backup, dry_run)
        if clean:
            _clean_sequence_files(dest, dry_run)
